# Generated by Django 4.1.5 on 2023-02-09 02:15

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgoCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST', models.CharField(max_length=100)),
                ('USER', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jenkins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST', models.CharField(max_length=100)),
                ('USER', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='K8s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50, validators=[pybo.models.name_validate])),
                ('KIND', models.CharField(max_length=50)),
                ('GIT', models.URLField(blank=True, validators=[pybo.models.git_validate])),
                ('GITTOKEN', models.CharField(blank=True, max_length=100, validators=[pybo.models.gittoken_validate])),
                ('SONARTOKEN', models.CharField(blank=True, max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
            ],
        ),
    ]
