# Generated by Django 4.1.5 on 2023-01-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('KIND', models.CharField(max_length=50)),
                ('GIT', models.CharField(max_length=200)),
                ('GITTOKEN', models.CharField(max_length=100)),
                ('SONARTOKEN', models.CharField(max_length=100)),
            ],
        ),
    ]
