# Generated by Django 4.1.5 on 2023-01-20 00:03

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='GIT',
            field=models.URLField(blank=True, validators=[pybo.models.git_validate]),
        ),
        migrations.AlterField(
            model_name='project',
            name='GITTOKEN',
            field=models.CharField(blank=True, max_length=100, validators=[pybo.models.gittoken_validate]),
        ),
        migrations.AlterField(
            model_name='project',
            name='NAME',
            field=models.CharField(max_length=50, validators=[pybo.models.name_validate]),
        ),
        migrations.AlterField(
            model_name='project',
            name='SONARTOKEN',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
