# Generated by Django 4.1.5 on 2023-01-26 01:43

import django.core.validators
from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_project_git_alter_project_gittoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='NAME',
            field=models.CharField(max_length=50, validators=[pybo.models.name_validate, django.core.validators.MinValueValidator(5, '5자리 이상 입력')]),
        ),
    ]
