# Generated by Django 4.1.5 on 2023-02-02 07:04

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgoCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST', models.CharField(max_length=100)),
                ('USER', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('TOKEN', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jenkins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST', models.CharField(max_length=100)),
                ('USER', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='NAME',
            field=models.CharField(max_length=50, validators=[pybo.models.name_validate]),
        ),
    ]
