# Generated by Django 4.1.5 on 2023-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_argocd_jenkins_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN', models.CharField(max_length=1200)),
            ],
        ),
        migrations.RemoveField(
            model_name='argocd',
            name='TOKEN',
        ),
    ]
